### ISSUE TITLE
Add Cloudi to the docs

### ISSUE THREAD

**Issue by ShalokShalom** [esl/Pyrlang#8]
Somebody in IRC tells me, that [Cloudi](http://cloudi.org) is suitable in order to handle throughput inbetween Python and Erlang, because Pyrlang is a single socket connection for distributed Erlang node communication: 

This project allows us to have multiple socket connections to python processes (and separate threads if you choose), Some comparison to cnodes is at http://cloudi.org/faq.html#4_Erlang

**Comment by kvakvs** [comment]
CloudI thingy looks like it is a separate RPC implementation, good for them!

This project is Erlang distributed protocol implementation which uses explicitly 1 socket only. But since it is a `gevent` library, and each Erlang Node object in Python is independent, you are free to start more than one Node. To Erlang they will look as different nodes - this is untested but in theory should work smoothly.
